build:
  image: golang:1.6
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - make vet
    - make build
    - make test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: registry.b4cc.com:5000/drone-ecs
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: registry.b4cc.com:5000/drone-ecs
    tag: develop
    when:
      branch: develop
